--e)eliminacion logica
ALTER TABLE DOCUMENTO
	ADD eliminado bit NOT NULL DEFAULT 0

ALTER TABLE VERSION 
	ADD eliminado bit NOT NULL DEFAULT 0

ALTER TABLE PARTICIPANTE 
	ADD eliminado bit NOT NULL DEFAULT 0

ALTER TABLE RELACION 
	ADD eliminado bit NOT NULL DEFAULT 0