ALTER TABLE DOCUMENTO ADD eliminado bit NOT NULL DEFAULT 0

ALTER TABLE PARTICIPANTE ADD eliminado bit NOT NULL DEFAULT 0

ALTER TABLE RELACION ADD eliminado bit NOT NULL DEFAULT 0

ALTER TABLE VRSION ADD eliminado bit NOT NULL DEFAULT 0