--CREATE DATABASE ParcialBD2;
--USE ParcialBD2

-- a) Generar las tablas
CREATE TABLE DOCUMENTO ( 
ID INT IDENTITY PRIMARY KEY,
TITULO VARCHAR(250) NULL,
TIPO CHAR(1),
VERSION_ACTUAL CHAR(8),
VENCIMIENTO DATETIME NULL )

CREATE TABLE PARTICIPANTE (
ID INT PRIMARY KEY,
ID_USUARIO_LDAP BIGINT, 
NOMBRE VARCHAR(255))

CREATE TABLE VERSION (
ID INT IDENTITY PRIMARY KEY,
ID_DOCUMENTO INT,
VERSION CHAR(8),
FECHA_CREACION DATETIME NULL,
FECHA_PUBLICACION DATETIME NULL, 
BORRADOR BIT, 
LINK_DOCUMENTO VARCHAR(255) NULL,
REFERENTE INT,
REVISOR INT,
APROBADOR INT NULL,
FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTO(ID),
FOREIGN KEY(REFERENTE) REFERENCES PARTICIPANTE(ID),
FOREIGN KEY(REVISOR) REFERENCES PARTICIPANTE(ID),
FOREIGN KEY(APROBADOR) REFERENCES PARTICIPANTE(ID))

CREATE TABLE RELACION(
ID INT IDENTITY PRIMARY KEY,
ID_DOCUMENTO_ORIGEN INT, 
ID_DOCUMENTO_DESTINO INT,
TIPO_RELACION CHAR(1),
FOREIGN KEY (ID_DOCUMENTO_ORIGEN) REFERENCES DOCUMENTO(ID),
FOREIGN KEY (ID_DOCUMENTO_DESTINO) REFERENCES DOCUMENTO(ID))
