CREATE DATABASE ParcialBD2;
USE ParcialBD2

-- a) Generar las tablas

CREATE TABLE DOCUMENTO ( 
ID INT IDENTITY PRIMARY KEY,
TITULO VARCHAR(250) NULL,
TIPO CHAR(1),
VERSION_ACTUAL CHAR(8),
VENCIMIENTO DATETIME NULL )

CREATE TABLE PARTICIPANTE (
ID INT PRIMARY KEY,
ID_USUARIO_LDAP BIGINT, 
NOMBRE VARCHAR(255))

CREATE TABLE VERSION (
ID INT IDENTITY PRIMARY KEY,
ID_DOCUMENTO INT,
VERSION CHAR(8),
FECHA_CREACION DATETIME NULL,
FECHA_PUBLICACION DATETIME NULL, 
BORRADOR BIT, 
LINK_DOCUMENTO VARCHAR(255) NULL,
REFERENTE INT,
REVISOR INT,
APROBADOR INT NULL,
FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTO(ID),
FOREIGN KEY(REFERENTE) REFERENCES PARTICIPANTE(ID),
FOREIGN KEY(REVISOR) REFERENCES PARTICIPANTE(ID),
FOREIGN KEY(APROBADOR) REFERENCES PARTICIPANTE(ID))

CREATE TABLE RELACION(
ID INT IDENTITY PRIMARY KEY,
ID_DOCUMENTO_ORIGEN INT, 
ID_DOCUMENTO_DESTINO INT,
TIPO_RELACION CHAR(1),
FOREIGN KEY (ID_DOCUMENTO_ORIGEN) REFERENCES DOCUMENTO(ID),
FOREIGN KEY (ID_DOCUMENTO_DESTINO) REFERENCES DOCUMENTO(ID))

--e) Agregar posibilidad de eliminación lógica de todas las entidades. Esto significa uncampo bit llamado “eliminado”, por defecto en 0 en todas las tablas

ALTER TABLE DOCUMENTO ADD ELIMINADO BIT NOT NULL DEFAULT 0
ALTER TABLE PARTICIPANTE  ADD ELIMINADO BIT NOT NULL DEFAULT 0
ALTER TABLE VERSION  ADD ELIMINADO BIT NOT NULL DEFAULT 0
ALTER TABLE RELACION  ADD ELIMINADO BIT NOT NULL DEFAULT 0

--f) Agregar auditoría sobre la tabla Versión, respecto a Referente, revisor y aprobador. Esto significa generar una tabla de auditoría y crear el/los artefacto(s) de desarrollo
--necesario(s) para que al modificar alguno de los tres nombrados, se guarde el valoranterior

CREATE TABLE AUDITORIA_VERSION(
ID INT NOT NULL, 
ID_DOCUMENTO INT,
REFERENTE INT,
REVISOR INT,
APROBADOR INT,

)


CREATE TABLE futuros_vencimientos
(
    orden INT IDENTITY(1,1),
    id_documento INT,
    vencimiento datetime
)

select*from PARTICIPANTE
select* from version
select * from DOCUMENTO
SELECT * FROM RELACION
select *  from AUDITORIA_VERSION
select * from futuros_vencimientos


insert into PARTICIPANTE values (1,565656,'Arturo',0)
insert into PARTICIPANTE values (2,5644456,'Marta',0)

insert into DOCUMENTO values('la mancha','a','v1','2021-17-02',0)
insert into DOCUMENTO values('la mancha 2','a','v1','2021-17-02',0)


insert into VERSION values(1,'v1','2019-01-01','2019-01-01',0,null,1,null,null,0)
insert into futuros_vencimientos values(4,GETDATE())